CREATE TABLE Respuestas (
    id BIGINT NOT NULL AUTO_INCREMENT,
    mensaje TEXT NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    topico_id BIGINT NOT NULL,
    autor_id BIGINT NOT NULL,
    solucion VARCHAR(255),
    PRIMARY KEY (id),
    FOREIGN KEY (topico_id) REFERENCES Topicos(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (autor_id) REFERENCES Usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);